dependencies:
  - name: stable/mongodb
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: stable/nginx-ingress
    repository: https://kubernetes-charts.storage.googleapis.com/
