service:
  type: ClusterIP
  externalPort: 80
  internalPort: 5000
  name: CLARA
  component: "clara"
deployment:
  replicas: 1
  imagePullPolicy: always
  cpu: "10m"
  memory: "128Mi"
  containerPort: 5000

## Ingress settings
ingress:
  enabled: true
  hostname: 13.68.131.17
  annotations:
     kubernetes.io/ingress.class: nginx
     certmanager.k8s.io/cluster-issuer: letsencrypt-prod
     kubernetes.io/tls-acme: "true"
  tls: true
