service:
  type: ClusterIP
  externalPort: 80
  internalPort: 5000
  name: CLARA
  component: "clara"
deployment:
  replicas: 1
  imagePullPolicy: always
  cpu: "10m"
  memory: "128Mi"
  containerPort: 5000

## Ingress settings
ingress:
  enabled: true
  hostname: clara-backend.eastus.cloudapp.azure.com
  annotations:
     kubernetes.io/ingress.class: nginx
     certmanager.k8s.io/issuer: letsencrypt-staging
     nginx.ingress.kubernetes.io/rewrite-target: /
  tls: true
